name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
        php:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
        dependencies:
          - "locked"
          - "lowest"
          - "highest"
        experimental:
          - false

    name: PHP${{ matrix.php }} on ${{ matrix.os }} (${{ matrix.dependencies }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo
          coverage: none

      - name: Install dependencies
        uses: "ramsey/composer-install@v1"
        with:
          composer-options: "--prefer-dist --no-cache"
      - name: Execute tests
        run: vendor/bin/phpunit
